spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/waf_pool_management?&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  # 当状态码为4xx时直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 关闭默认的静态资源路径映射
  web:
    resources:
      add-mappings: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.maoxian.pojo
logging:
  level:
    root: info
    com.maoxian.mapper: debug
