server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/waf_pool_management?&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  # 当状态码为4xx时直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 关闭默认的静态资源路径映射
  web:
    resources:
      add-mappings: false
  mail:
    host: smtp.qq.com
    port: 587
    username: 2425074199@qq.com
    password: mzbleoodpqrrdjeb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
    default-encoding: UTF-8
    protocol: smtp
    valid: 5
  thymeleaf:
    cache: false
    mode: LEGACYHTM5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.maoxian.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.maoxian.mapper: debug

